services:
  mysql:
    image: mysql:8.0
    container_name: sentinela-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_local
      MYSQL_DATABASE: sentinela
      MYSQL_USER: sentinela
      MYSQL_PASSWORD: sentinela_local
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - sentinela-dados:/var/lib/mysql
    command: --default-time-zone=-03:00
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sentinela-dados:
